//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformWcfDemo2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddTicket", ReplyAction="http://tempuri.org/IService2/AddTicketResponse")]
        void AddTicket(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/AddTicket", ReplyAction="http://tempuri.org/IService2/AddTicketResponse")]
        System.Threading.Tasks.Task AddTicketAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/BuyTickets", ReplyAction="http://tempuri.org/IService2/BuyTicketsResponse")]
        int BuyTickets(int Num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/BuyTickets", ReplyAction="http://tempuri.org/IService2/BuyTicketsResponse")]
        System.Threading.Tasks.Task<int> BuyTicketsAsync(int Num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetRemainingNum", ReplyAction="http://tempuri.org/IService2/GetRemainingNumResponse")]
        int GetRemainingNum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GetRemainingNum", ReplyAction="http://tempuri.org/IService2/GetRemainingNumResponse")]
        System.Threading.Tasks.Task<int> GetRemainingNumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : WinformWcfDemo2.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<WinformWcfDemo2.ServiceReference1.IService2>, WinformWcfDemo2.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTicket(int count) {
            base.Channel.AddTicket(count);
        }
        
        public System.Threading.Tasks.Task AddTicketAsync(int count) {
            return base.Channel.AddTicketAsync(count);
        }
        
        public int BuyTickets(int Num) {
            return base.Channel.BuyTickets(Num);
        }
        
        public System.Threading.Tasks.Task<int> BuyTicketsAsync(int Num) {
            return base.Channel.BuyTicketsAsync(Num);
        }
        
        public int GetRemainingNum() {
            return base.Channel.GetRemainingNum();
        }
        
        public System.Threading.Tasks.Task<int> GetRemainingNumAsync() {
            return base.Channel.GetRemainingNumAsync();
        }
    }
}
